sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t myk3s/docker-react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true myk3s/docker-react-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-923445559289"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
